healthcare_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: 'healthcare-data-project-477711' # My GCP PROJECT ID
      dataset: healthcare_data
      threads: 4
      keyfile: /usr/app/gcp_credentials.json
      timeout_seconds: 300
      priority: interactive
      retries: 1